language: python
fast_finish: true

python:
  - 2.7
  - 3.6

os:
  - linux

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - pip -q install coveralls
    # temp for pip < 9.1
    - pip -q install numpy

install: pip install -e . --process-dependency-links

script: coverage run tests/test.py -v

after_success: coveralls
